---
title: "downscale"
author: "ayrton"
date: "2025-07-18"
output: html_document
---

```{r pacotes}
pacman::p_load(ecmwfr,tidyverse,purrr,lubridate,ncdf4)
```

#### Baixando reanálise


```{r shape_AreaDeInteresse, include=FALSE}

shape <- geobr::read_health_region() %>% 
  filter(abbrev_state == "SC" & name_health_region == "Nordeste") # mudar aqui de acordo com o interesse

aoi_bb <- sf::st_bbox(shape)

shape_dis <- read_sf("./Joishapes/joiDistritos/joiDistr.shp")

```

#### Downscaling

```{r downscale_funcoes_pacotes}

source("./funcoes_extras_downscale.R")

pacman::p_load(terra,raster,geobr,INLA,kableExtra,
               reshape2,tidyverse, sf)
```

```{r carregando_reanalise}

#list.files(path = "./reanalysis(epiweek)/")
semana_interesse <- 36

# Reading and cropping reanalysis ERA data
netcdf_reanalysis <- list.files(
  "./reanalysis(epiweek)/",
  pattern ="\\036.nc$", # selecionar aqui a(s) semana(s) de interesse
  full.names = TRUE
  )

reanalysis_rasters <- lapply(
  netcdf_reanalysis,
  process_netcdf
  )

initial_year <- as.numeric(substr(terra::time(reanalysis_rasters[[1]]),1,4))
```

```{r combinando_em_df}

# Converting SpatRaster to data.frame and combining then into a single data.frame
df_reanalysis <- lapply(
  reanalysis_rasters,
  convert_to_dataframe
  )

df_reanalysis <- bind_rows(
  df_reanalysis,
  .id = "year") %>% 
     tibble() %>% 
     mutate(
       year = initial_year - 1 + as.numeric(year)
  )

```

```{r criando_malha}

coords <- cbind(df_reanalysis$x, df_reanalysis$y)
boundary <- inla.nonconvex.hull(st_coordinates(shape)[, 1:2])

mesh <- inla.mesh.2d(
  loc = coords,
  boundary = shape,
  max.edge = c(0.5,1),
  offset = c(0.5, 1),
  cutoff = 0.1
  )
```


```{r definindo_modelo}

spde <- inla.spde2.pcmatern(
  mesh,
  alpha = 2, 
  constr = TRUE,
  prior.range = c(50, 0.5), # P(range < 10000) = 0.01
  prior.sigma = c(3, 0.01) # P(sigma > 3) = 0.01)
)

timesn <- length(unique(df_reanalysis$year))
indexs <- inla.spde.make.index("s",
                               n.spde = spde$n.spde,
                               n.group = timesn
)

group <- as.numeric(factor(df_reanalysis$year, levels = unique(df_reanalysis$year), labels = 1:length(unique(df_reanalysis$year))))
A <- inla.spde.make.A(mesh = mesh, loc = coords, group = group)

stk.e <- inla.stack(
  tag = "est",
  data = list(y = df_reanalysis$values),
  A = list(1, A),
  effects = list(
    data.frame(
      b0 = rep(1, nrow(df_reanalysis)),
      year = factor(df_reanalysis$year, levels = unique(df_reanalysis$year))
    ), 
    s = indexs)
)

bb <- st_bbox(shape)
x <- seq(bb$xmin - 1, bb$xmax + 1, length.out = 500)
y <- seq(bb$ymin - 1, bb$ymax + 1, length.out = 500)
dp <- as.matrix(expand.grid(x, y))

p <- st_as_sf(data.frame(x = dp[, 1], y = dp[, 2]),
              coords = c("x", "y"))
st_crs(p) <- st_crs(shape)
ind <- st_intersects(shape, p)
dp <- dp[ind[[1]], ]

final_dp = NULL
for(i in unique(group)){
  temp_dp <- cbind(dp, Var3 = i)
  final_dp <- rbind(final_dp, temp_dp)
}

coop <- final_dp[, 1:2]
groupp <- final_dp[, 3]
final_dp <- final_dp %>% 
  data.frame() %>% 
  mutate(
    year = Var3,
    year = factor(year,
                  levels = unique(group),
                  labels = unique(df_reanalysis$year)
    )
  )

Ap <- inla.spde.make.A(mesh = mesh, loc = coop, group = groupp)

stk.p <- inla.stack(
  tag = "pred",
  data = list(y = NA),
  A = list(1, Ap),
  effects = list(
    data.frame(
      b0 = rep(1, nrow(final_dp)),
      year = final_dp$year
    ),
    s = indexs)
)

stk.full <- inla.stack(stk.e, stk.p)
rprior <- list(theta = list(prior = "pccor1", param = c(0.5, 0.9)))

formula <- y ~ 0 + b0 + year + f(s,
                                 model = spde, group = s.group,
                                 control.group = list(model = "ar1", hyper = rprior)
)

```

```{r rodando_modelo}

res <- inla(
  formula,
  data = inla.stack.data(stk.full),
  control.predictor = list(
          compute = TRUE,
          A = inla.stack.A(stk.full)
        )
  )

```

```{r verificando_ajuste}

result_inla <- summary(res)

result_inla$fixed %>% 
  data.frame() %>% 
  mutate(
    lower_ci = mean - 1.96 * sd,
    upper_ci = mean + 1.96 * sd
  ) %>% 
  relocate(lower_ci, .after = mean) %>% 
  relocate(upper_ci, .after = lower_ci) %>% 
  dplyr::select(mean:sd, mode, kld) %>% 
  knitr::kable(caption = paste0("Tabela: Efeitos fixos do modelo INLA."),
               row.names = T,
               col.names = c("Média", "IC inf.", "IC sup.", "DP", "Moda", "KLD"),
               align = "c",
               digits = 2,
               format = "html") %>%
  kableExtra::kable_classic(full_width = F, html_font = "Cambria") %>% 
  row_spec(0, bold = T)

result_inla$hyperpar %>% 
  data.frame() %>% 
  knitr::kable(caption = paste0("Tabela: Efeitos fixos do modelo INLA."),
               row.names = T,
               col.names = c("Média", "DP", "Q(2.75)", "Mediana", "Q(97.5)", "Moda"),
               align = "c",
               digits = 2,
               format = "html") %>%
  kableExtra::kable_classic(full_width = F, html_font = "Cambria") %>% 
  row_spec(0, bold = T)
```

```{r marginais_modelo, eval=FALSE, include=FALSE}

list_marginals <- list(
  "b0" = res$marginals.fixed$b0,
  "2000" = res$marginals.fixed$year2000,
  "2001" = res$marginals.fixed$year2001,
  "2002" = res$marginals.fixed$year2002,
  "2003" = res$marginals.fixed$year2003,
  "2004" = res$marginals.fixed$year2004,
  "2005" = res$marginals.fixed$year2005,
  "2006" = res$marginals.fixed$year2006,
  "2007" = res$marginals.fixed$year2007,
  "2008" = res$marginals.fixed$year2008,
  "2009" = res$marginals.fixed$year2009,
  "2010" = res$marginals.fixed$year2010,
  "2011" = res$marginals.fixed$year2011,
  "2012" = res$marginals.fixed$year2012,
  "2013" = res$marginals.fixed$year2013,
  "2014" = res$marginals.fixed$year2014,
  "2015" = res$marginals.fixed$year2015,
  "2016" = res$marginals.fixed$year2016,
  "2017" = res$marginals.fixed$year2017,
  "2018" = res$marginals.fixed$year2018,
  "2019" = res$marginals.fixed$year2019,
  "2020" = res$marginals.fixed$year2020,
  "2021" = res$marginals.fixed$year2021,
  "2022" = res$marginals.fixed$year2022,
  "2023" = res$marginals.fixed$year2023,
  "precision Gaussian obs" =
    res$marginals.hyperpar$"Precision for the Gaussian observations",
  "range" = res$marginals.hyperpar$"Range for s",
  "stdev" = res$marginals.hyperpar$"Stdev for s",
  "rho" = res$marginals.hyperpar$"GroupRho for s"
)

marginals <- data.frame(do.call(rbind, list_marginals))
marginals$parameter <- factor(
  rep(names(list_marginals),
      times = sapply(list_marginals, function(x) if (is.null(dim(x))) length(x) else nrow(x))
  ),
  levels = names(list_marginals)
)

g_marginals <- marginals %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_line() +
  labs(x = "", y = "Density") + 
  theme_bw() +
  facet_wrap(~parameter, scales = "free", ncol = 3); g_marginals
```

```{r plotando_resultados}

index <- inla.stack.index(stack = stk.full, tag = "pred")$data
final_dp <- data.frame(final_dp) %>% 
  set_names(c("x", "y", "time", "year"))

final_dp$pred_mean <- res$summary.fitted.values[index, "mean"]
final_dp$pred_ll <- res$summary.fitted.values[index, "0.025quant"]
final_dp$pred_ul <- res$summary.fitted.values[index, "0.975quant"]

df_interpolate <- melt(final_dp,
                       id.vars = c("x", "y", "time", "year"),
                       measure.vars = c("pred_mean", "pred_ll", "pred_ul")
)


# gg_mean <- gg_interpolate(
#   sf = shape,
#   df_interpolate = df_interpolate,
#   var = "pred_mean",
#   facet_var = "year"
#   ) +
#   labs(title = "ERJ - ERA5 (downscaled)",
#        subtitle = "pred_mean"); gg_mean
# 
# gg_pred_ll <- gg_interpolate(
#   sf = shape,
#   df_interpolate = df_interpolate,
#   var = "pred_ll",
#   facet_var = "year"
#   ) +
#   labs(title = "ERJ - ERA5 (downscaled)",
#        subtitle = "pred_ll"); gg_pred_ll
# 
# gg_pred_ul <- gg_interpolate(
#   sf = shape,
#   df_interpolate = df_interpolate,
#   var = "pred_ul",
#   facet_var = "year"
#   ) +
#   labs(title = "ERJ - ERA5 (downscaled)",
#        subtitle = "pred_ul"); gg_pred_ul
```

```{r cortar_para_municipio}
# Converter df_interpolate para objeto sf (pontos)
# More efficient approach using spatial joins and avoiding unnecessary operations
pontos_dentro <- st_join(
  st_as_sf(df_interpolate, coords = c("x", "y"), crs = st_crs(shape_dis)),
  shape_dis,
  join = st_intersects,
  left = FALSE  # Only keep points that intersect
)

# Extract coordinates and create final dataframe in one step
df_jv <- pontos_dentro %>%
  mutate(
    lon = st_coordinates(.)[, "X"],
    lat = st_coordinates(.)[, "Y"]
  ) %>%
  st_drop_geometry() %>%
  #select(-c(code_state, abbrev_state,time)) %>% 
  as.data.frame()

```

```{r resumo_por_epiweek}

# names_from = "usar a variável de estratificação do shape (aqui não tem, somente para o município inteiro)"

 res_epiweek_36 <-  df_jv  %>%
  pivot_wider(names_from = "variable", 
              values_from = "value") %>% 
  group_by(year,Distrito) %>% 
  summarise(mean_pred = mean(pred_mean),
            mean_ll = mean(pred_ll),
            pred_ul = mean(pred_ul)) %>% 
  mutate(SE = paste0(year,semana_interesse)) %>% 
  ungroup() %>% 
  select(-year)

dist_temp_min_ate36 <- rbind(res_epiweek_28,res_epiweek_29,
      res_epiweek_30,res_epiweek_31,
      res_epiweek_32,res_epiweek_33,
      res_epiweek_33,res_epiweek_34,
      res_epiweek_35,res_epiweek_36)

write.csv(dist_temp_min_ate36,"./dist_temp_min_ate36.csv")

```

